DROP TABLE MANAGER_REFRESH_TOKEN;

CREATE TABLE MANAGER_REFRESH_TOKEN (
  MNNO        NUMBER(10)    NOT NULL,
  TOEKN       VARCHAR2(500) NOT NULL,
  EXPIRY_DATE VARCHAR2(19)  NOT NULL,
  CDATE       VARCHAR2(19)  NOT NULL,

  PRIMARY KEY (MNNO),
  FOREIGN KEY (MNNO) REFERENCES MANAGER(NO) ON DELETE CASCADE
);