DROP TABLE SHOP_INVITE_CODE;

CREATE TABLE SHOP_INVITE_CODE(
  SNO           NUMBER(7)     NOT NULL,
  CODE          VARCHAR2(6)   UNIQUE NOT NULL,
  EXPIRY_DATE   VARCHAR2(19)  NOT NULL,
  CDATE         VARCHAR2(19)  NOT NULL,

  PRIMARY KEY(SNO),
  FOREIGN KEY(SNO) REFERENCES SHOP(NO) ON DELETE CASCADE
)