DROP TABLE SHOP_MEMBER;

CREATE TABLE SHOP_MEMBER(
  NO     NUMBER(10)   NOT NULL,
  SNO    NUMBER(10)   NOT NULL,
  MNO    NUMBER(10)   NOT NULL,
  CDATE  VARCHAR2(19) NOT NULL,

  PRIMARY KEY (NO),
  FOREIGN KEY (MNO) REFERENCES MEMBER(NO) ON DELETE CASCADE,
  FOREIGN KEY (SNO) REFERENCES SHOP(NO) ON DELETE CASCADE
);

DROP SEQUENCE SHOP_MEMBER_SEQ;

CREATE SEQUENCE SHOP_MEMBER_SEQ START WITH 1 INCREMENT BY 1;