DROP TABLE MEMBER_REFRESH_TOKEN;

CREATE TABLE MEMBER_REFRESH_TOKEN (
  MNO         NUMBER(10)    NOT NULL,
  TOEKN       VARCHAR2(500) NOT NULL,
  EXPIRY_DATE VARCHAR2(19)  NOT NULL,
  CDATE       VARCHAR2(19)  NOT NULL,

  PRIMARY KEY (MNO),
  FOREIGN KEY (MNO) REFERENCES MEMBER(NO) ON DELETE CASCADE
);