CREATE TABLE MANAGER_UPDATELOG (
	NO						NUMBER(10)		NOT NULL,      -- 관리자 업데이트 로그 번호
	MNNO					NUMBER(10)			NOT NULL,      -- 관리자 번호
	CHANGED_COLUMN	VARCHAR2(50)	NOT NULL,   	 -- 변경한 항목
	OLD_VALUE			VARCHAR2(100)	NULL,       	 -- 변경 전 값
	NEW_VALUE			VARCHAR2(100)	NOT NULL,      -- 변경 후 값
	CHANGE_DATE		VARCHAR2(19) 	NOT	NULL,      -- 변경 일시
	UPDT_MNNO			NUMBER(10)		NOT NULL,      -- 변경한 관리자 ID

  PRIMARY KEY (NO),
  FOREIGN KEY (MNNO) REFERENCES MANAGER(NO),
	FOREIGN KEY (UPDT_MNNO) REFERENCES MANAGER(NO)
);

DROP TABLE MANAGER_UPDATELOG;

CREATE SEQUENCE MANAGER_UPDATELOG_SEQ START WITH 1 INCREMENT BY 1;